# Generated by Django 2.2.4 on 2020-12-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Semi_Restful_TV_Shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Network',
            new_name='network',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Release_Date',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Title',
            new_name='title',
        ),
    ]
